<a href="https://colab.research.google.com/github/Aditya9790/Machine-Learning/blob/main/ML_Modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a = np.array([[1,2,10,44,10], [1,2,3,4,5]])
print(np.ndim(a)) # dimention of array
print(np.shape(a)) # size of array in the form of (m, n)

2
(2, 5)


In [ ]:
b = np.arange(1, 100, 22)
print(b)

[ 1 23 45 67 89]


In [ ]:
one = np.ones((2,6))
print(one)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
rand_num = np.random.rand(4,2) # uniformly distributed numbers
print(rand_num)# from [0,1)

[[0.1910144  0.7879322 ]
 [0.17666387 0.57712752]
 [0.68395069 0.48794614]
 [0.1484124  0.47063042]]


In [ ]:
rand_normal = np.random.randn(4,2) # normally distributed numbers
print(rand_normal)# from [0,1)

[[ 0.4459046  -0.60413406]
 [-1.49964317  1.06513458]
 [-0.31593075 -1.14559999]
 [ 0.28778377 -1.56442553]]


In [ ]:
rand_int = np.random.randint(2, 100, 12).reshape(3,4) # generated 10 random integers
print(rand_int)# from 2, 100
print(f'Dimention of rand_int is : {rand_int.ndim}')

[[77  8 63 51]
 [12 85 76 99]
 [14 26 97 58]]
Dimention of rand_int is : 2


In [ ]:
rand_int[0,1:]

array([ 8, 63, 51])

# **Pandas**

In [ ]:
arr = np.random.randint(-10, 10, 20).reshape(4, 5) # random matrix of (4, 5) size

In [ ]:
# create a data frame
df = pd.DataFrame(arr, index = 'A B C D'.split(), columns = 'V W X Y Z'.split())
print(df)

   V  W  X  Y  Z
A -2  6  8 -7 -6
B  3  2  7  1 -4
C -6  6  5 -6 -5
D  8 -6  9 -5 -3


In [ ]:
df.index[0]

'A'

Generally we access the data frame by column names and not by row names

In [ ]:
df['W']

A    6
B    2
C    6
D   -6
Name: W, dtype: int64

To access two columns at the same time pass the column names as a list.

**NOTE :** 
Order is not important we can pass columns in any order as we like.

In [ ]:
df[['W', 'X', 'Y']]

W  X  Y
A  6  8 -7
B  2  7  1
C  6  5 -6
D -6  9 -5

To access the rows we use **loc** function, in loc we pass the row names.

We can access columns by **iloc** function, here we pass column index as a parameter

In [ ]:
df.loc[['A', 'B']]

V  W  X  Y  Z
A -2  6  8 -7 -6
B  3  2  7  1 -4

In [ ]:
df.iloc[[0, 1], [0, 2]]

V  X
A -2  8
B  3  7

In [ ]:
df.loc[['A'], ['V', 'W']]

V  W
A -2  6

In [ ]:
df

V  W  X  Y  Z
A -2  6  8 -7 -6
B  3  2  7  1 -4
C -6  6  5 -6 -5
D  8 -6  9 -5 -3

In [ ]:
df['W']<0

A    False
B    False
C    False
D     True
Name: W, dtype: bool

In [ ]:
a = df['W']<0
a

A    False
B    False
C    False
D     True
Name: W, dtype: bool

In [ ]:
df[a]

V  W  X  Y  Z
D  8 -6  9 -5 -3

In [ ]:
# Create a data frame
Employee1 = {'Sr No':[1,2,3,4,5], 'Name':['Aditya', 'Michel', 'Mark', 'Abby', 'Lara'], 'Monthly Salary':[90000, 100000, 80000, 76000, 87000]}
Table1 = pd.DataFrame(Employee1)
Table1.set_index('Sr No', inplace=True)
print(Table1)

         Name  Monthly Salary
Sr No                        
1      Aditya           90000
2      Michel          100000
3        Mark           80000
4        Abby           76000
5        Lara           87000


In [ ]:
Employee2 = {'Sr No':[1,2,3,4,5], 'Name':['AdityaGole', 'Michel', 'Mark', 'Abby', 'Lara'], 'Monthly Salary':[90000, 100000, 80000, 76000, 87000]}
Table2 = pd.DataFrame(Employee2)
Table2.set_index('Sr No', inplace=True)
print(Table2)

             Name  Monthly Salary
Sr No                            
1      AdityaGole           90000
2          Michel          100000
3            Mark           80000
4            Abby           76000
5            Lara           87000


Merging of two Tables

In [ ]:
# This merges the columns which are identical to eachother.
# if any entry is not identical it drops it
# as here 1 st entry od Table1 and Table2 is not same so it drops the entire entry.
combined_employee_data = pd.merge(Table1, Table2)
print(combined_employee_data)

   Sr No    Name  Monthly Salary
0      2  Michel          100000
1      3    Mark           80000
2      4    Abby           76000
3      5    Lara           87000


# **Import file from google drive**

In [ ]:
from google.colab import drive
drive.mount("/content/drive/", force_remount=True)

Mounted at /content/drive/


In [ ]:
ipl_data = '/content/drive/MyDrive/Colab Notebooks/IPL IMB381IPL2013.csv'
ipl_df = pd.read_csv(ipl_data)
print('First 3 rows are:')
ipl_df.head(3)


First 3 rows are:


Sl.NO.   PLAYER NAME  AGE  ... AUCTION YEAR BASE PRICE SOLD PRICE
0       1   Abdulla, YA    2  ...         2009      50000      50000
1       2  Abdur Razzak    2  ...         2008      50000      50000
2       3   Agarkar, AB    2  ...         2008     200000     350000

[3 rows x 26 columns]

In [ ]:
ipl_df[['Sl.NO.', 'PLAYER NAME','COUNTRY', 'TEAM']].head(5)

Sl.NO.   PLAYER NAME COUNTRY  TEAM
0       1   Abdulla, YA      SA  KXIP
1       2  Abdur Razzak     BAN   RCB
2       3   Agarkar, AB     IND   KKR
3       4     Ashwin, R     IND   CSK
4       5  Badrinath, S     IND   CSK

In [ ]:
# create the csv file into html code
ipl_df.to_html("IPL.html")
ipl_html = open('/content/IPL.html', 'r')
read_ipl = ipl_html.read()

In [ ]:
ipl_df.iloc[[0,1,2], [0,1,2]]

Sl.NO.   PLAYER NAME  AGE
0       1   Abdulla, YA    2
1       2  Abdur Razzak    2
2       3   Agarkar, AB    2